name = "milkv-led"
main = "target/wasm32-wasip2/release/milkv-led.wasm"
type = "cli"

[[dependencies]]
version = "0.1.0"
kind = "native"
oci = "ghcr.io/yieldspace/imago/experimental-gpio"

[resources.gpio]
digital_pins = [
    { label = "GPI459", value_path = "/sys/class/gpio/gpio459/value", supports_input = false, supports_output = true, default_active_level = "active-high", allow_pull_resistor = true },
]

[build]
command = "cargo build --target wasm32-wasip2 --release"

[capabilities]
wasi = true

[target.default]
remote = "192.168.42.1:4443"
client_key = "certs/client.key"

[capabilities.deps]
"imago:experimental-gpio" = ["*"]
