name = "milkv-led"
main = "target/wasm32-wasip2/release/milkv-led.wasm"
type = "cli"

[[dependencies]]
version = "0.2.0"
kind = "native"
oci = "ghcr.io/yieldspace/imago/usb"

[build]
command = "cargo build --target wasm32-wasip2 --release"

[[assets]]
path = "assets/captures/.gitkeep"

[[assets]]
path = "assets/models/yolo.cvimodel"

[[assets]]
path = "assets/models/coco.names"

[[assets]]
path = "assets/models/yolo.toml"

[[resources.mounts]]
asset_dir = "assets/captures"
guest_path = "/captures"

[[resources.read_only_mounts]]
asset_dir = "assets/models"
guest_path = "/app/assets/models"

[resources.usb]
paths = [
    "/dev/bus/usb/001/002",
]

[capabilities]
wasi = true

[capabilities.deps]
"imago:usb" = ["*"]

[target.default]
remote = "ssh://root@192.168.2.4"
