package sizumita:milkv-led;

world plugin-imports {
    import imago:usb/provider@0.2.0;
    import imago:usb/device@0.2.0;
    import imago:usb/usb-interface@0.2.0;
    import wasi:nn/tensor@0.2.0-rc-2024-10-28;
    import wasi:nn/graph@0.2.0-rc-2024-10-28;
    import wasi:nn/inference@0.2.0-rc-2024-10-28;
    import wasi:nn/errors@0.2.0-rc-2024-10-28;
}
